version: "3.8"

services:
  database-service:
    build: ./database-service
    container_name: database-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/connections_db
      - PORT=3001
    depends_on:
      - mongo

  https-connection_service:
    build: ./https-connection-service
    container_name: https-connection-service
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=data_topic
      - PORT=3002
    ports:
      - "3002:3002"
    depends_on:
      - kafka

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"


  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"