version: "3.8"

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    environment:
      - DATABASE_SERVICE_URL=http://database-service:3001
      - HTTPS_CONNECTION_SERVICE_URL=http://https-connection-service:3002
      - QUERY_SERVICE_URL=http://query-service:3004
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - database-service
      - https-connection-service
      - query-service

  database-service:
    build: ./database-service
    container_name: database-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/connections_db
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  https-connection-service:
    build: ./https-connection-service
    container_name: https-connection-service
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=test_topic
      - PORT=3002
    ports:
      - "3002:3002"
    depends_on:
      - kafka

  kafka-consumer-service:
    build: ./kafka-consumer-service
    container_name: kafka-consumer-service
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=test_topic
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_DB=test_db
      - INFLUXDB_USER=username
      - INFLUXDB_PASSWORD=password
    ports:
      - "3003:3003"
    depends_on:
      - kafka
      - influxdb

  query-service:
    build: ./query-service
    container_name: query-service
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_DB=test_db
      - INFLUXDB_USER=username
      - INFLUXDB_PASSWORD=password
      - PORT=3004
    ports:
      - "3004:3004"
    depends_on:
      - influxdb

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]


  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_ADMIN_USER: username
      INFLUXDB_ADMIN_PASSWORD: password
      INFLUXDB_DB: test_db

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_PORT: 9000
    depends_on:
      - kafka

  chronograf:
    image: chronograf:1.8
    container_name: chronograf
    ports:
      - "8888:8888"
    depends_on:
      - influxdb
    environment:
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_USERNAME: username
      INFLUXDB_PASSWORD: password
